### ISSUE TITLE
Unbrauchbar seit dem letzten Update

### ISSUE THREAD

**Issue by clajog** [thomasloven/lovelace-layout-card#127]
Wie kann man man nur Befehle löschen??

Seit dem letztem Update ist die Card unbrauchbar geworden.
Der break Befehl war eines der wichtigsten Kommandos für mich.
Damit konnte ich das Layout so einstellen wie ich es brauchte.

Und nun - den break-Befehl gibt es nicht mehr :(
Vielen Dank dafür - als Programmierer sollte man einfach wissen, dass man so etwas nicht macht

**Comment by thomasloven** [comment]
English, please.

Also:
- Please take a look at <https://semver.org/> for what to expect when something suddenly changes major version number.
- Please take a look at the readme for this project for how to use the `layout-break` card or any other functionality - which is all still there.
- Please actually READ the release notes. Especially if they are titles "BREAKING!"
- Please let me know where exactly I forced you to update. I'll immediately remove that.

**Comment by clajog** [comment]
I don't speak English, translation from google.

Mistake 1:
max_columns: 2
Are displayed 3

Mistake 2:
the -break command no longer works

See also the pictures 

![Unbenannt](https://user-images.githubusercontent.com/76904096/111916365-dccd0900-8a7a-11eb-8287-5ab9c949bed1.png)
![Unbenannt1](https://user-images.githubusercontent.com/76904096/111916366-dfc7f980-8a7a-11eb-8066-61588e34fe12.png)

**Comment by NinDTendo** [comment]
"Und nun - den break-Befehl gibt es nicht mehr :(
Vielen Dank dafür - als Programmierer sollte man einfach wissen, dass man so etwas nicht macht"

Lies die Release Notes bevor du dich beschwerst. Dein Sarkasmus ist komplett fehl am Platz. Und anstatt thomasloven indirekt einen "schlechten" Programmierer zu nennen solltest du ihm danken, dass er überhaupt sich die Zeit nimmt derartige custom integration/cards zu machen. Wenn du es nicht mal schaffst die BREAKING NOTES zu lesen, dann kann man wohl folgern, dass du absolut keine Ahnung von "Programmiererei" hast.

english:
Read the release notes before complaining. Your sarcasm is out of place. Instead of implying that thomasloven is a "bad programmer" u should be thankful that he even takes the time to cretae such custom integration/cards. If you cant even read the BREAKING NOTES, it is deduceable that you have absolutely no clue what "programming" is.
