### ISSUE TITLE
Multiple columns divs

### ISSUE THREAD

**Issue by igloo15** [thomasloven/lovelace-layout-card#24]
Maybe this is intended or against lovelace guidelines but I noticed you create a new columns div inside your lovelace-layout-card dom element. You then add all your new columns/rows to that element. 

The issue is that you end up with a dom structure like this:

```
<hui-view>
       <style></style>
       <div id="columns">
              <div class="column">
                  <lovelace-layout-card>
                        <div id="columns">
                             <div class="column">
                                  //cards here
                             </div>
                        </div>
                  </lovelace-layout-card>
              </div>
       </div>
</hui-view>
```
You then apply a 500 maxWidth to class column which I believe may affect the column above lovelace-layout-card. 

By modifying the code to instead of doing

``` 
this.shadowroot.querySelector("#columns")
```

you do this

```
this.parentElement.parentElement
```

You will be modifying and controlling the generation of the root columns. Obviously this only works if the layout-card is used as your root card for the view as it will mess up any other cards that might exist outside layout-card. I haven't done enough testing with different setups to determine how widely applicable this solution is. 

The benefits though are that you no longer need to set `panel:true` which is great if you want to see badges and also do layout.

If your interested I could clean up my changes and submit a pull request. If you think its not a good idea for this card or violates design rules for cards on lovelace you can just close this issue.

Thanks!

**Comment by thomasloven** [comment]
Thanks for the idea.
The original reason I made layout-card was actually to use it in a stack rather than in panel mode. The idea was to have a glance card with some entities as a header but be able to keep the normal column layout below it (it was known as column-card back then). That's why it works like it does.

As you say, this will mess things up if you have other cards beside layout-card - such as in the advanced examples in the readme...

I actually already have plans for a new plugin which, rather than being a card that handles layouts, changes the way the default view elemen (`<hui-view>`) works.
(Much in the same way as [card-mod](https://github.com/thomasloven/lovelace-card-mod) changes the way all cards work)
I don't know when I'll get time to do it, or if it will even work, but keep your eyes open.
